---
# This role contains the installation of useful tools for the server


- name: install some useful tools
  yum: name={{ item }} state=present
  with_items:
    - vim
    - curl
    - wget
    - unzip
    - sshpass
    - telnet
    - libssh2
    - libssh2-devel
    - vim-X11
    - vim-common
    - vim-enhanced
    - vim-minimal
